//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCore.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebCore.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;WebAutotests&gt;
        ///  &lt;QA&gt;
        ///    &lt;RunSettings&gt;
        ///      &lt;Browser&gt;Chrome&lt;/Browser&gt;
        ///      &lt;Environment&gt;QA&lt;/Environment&gt;
        ///      &lt;Username&gt;mira.sopina1@gmail.com&lt;/Username&gt;
        ///      &lt;Password&gt;Dkht?dkjh123123&lt;/Password&gt;
        ///      &lt;BaseUrl&gt;https://www.google.com/drive/&lt;/BaseUrl&gt;
        ///    &lt;/RunSettings&gt;
        ///    &lt;EmailSettings&gt;
        ///    &lt;/EmailSettings&gt;
        ///    &lt;DbSettings&gt;
        ///    &lt;/DbSettings&gt;
        ///  &lt;/QA&gt;
        ///  &lt;DEV&gt;
        ///    &lt;RunSettings&gt;
        ///      &lt;Browser&gt;Chrome&lt;/Browser&gt;
        ///      &lt;Environment&gt;DEV&lt;/Environment&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GlobalConfig {
            get {
                return ResourceManager.GetString("GlobalConfig", resourceCulture);
            }
        }
    }
}
